# roles get branched from here
# Note: Optionally comment out any sections to pick and choose what gets run

# Deploy the VMs
- hosts: localhost
  vars_files:
    - vars.yml
  roles:
    - role: setup-ec2

# Create a Zone
- hosts: hubRouterNode
  vars_files:
    - vars.yml
  roles:
    - role: create-zone

# Deploy and start the hub router
- hosts: hubRouterNode
  vars_files:
    - vars.yml
  roles:
    - role: deploy-hub-router

# Deploy and start the agent
- hosts: apexNodes
  vars_files:
    - vars.yml
  roles:
    - role: deploy-mesh

# Validate nodes by running a connectivity test from the spoke node for QA e2e deployment
- hosts:  "{{ groups['apexNodes'][0] }}"
  vars_files:
    - vars.yml
  roles:
    - role: validate-connectivity
